version: "3.7"
services:
#    app:
#        build:
#            args:
#                user: sammy
#                uid: 1000
#            context: ./
#            dockerfile: Dockerfile
#        image: kefirium-auth
#        container_name: kefirium-auth-app
#        hostname: "$APP_NAME.$BASE_DOMAIN"
#        environment:
#            VIRTUAL_HOST: "$APP_NAME.$BASE_DOMAIN"
#            VIRTUAL_PORT: "80"
#        working_dir: /var/www/
#        volumes:
#            - ./:/var/www
#        networks:
#            - kefirium-auth
    db:
        image: postgres
        container_name: kefirium-auth-db
        environment:
            POSTGRES_DB: auth
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: postgres
        volumes:
            - ./docker-compose/postgresql:/var/lib/postgresql/data
        networks:
            - kefirium-auth
#    nginx:
#        image: nginx:alpine
#        container_name: kefirium-auth-nginx
#        ports:
#            - 8001:80
#        volumes:
#            - ./:/var/www
#            - ./docker-compose/nginx:/etc/nginx/conf.d/
#        networks:
#            - kefirium-auth

networks:
    kefirium-auth:
        driver: bridge
